### ISSUE TITLE
prefix configuration  option for cache keys

### ISSUE THREAD

**Issue by ezerdemello** [jaredwray/cache-manager#665]
**Is your feature request related to a problem? Please describe.**

I'm implementing a cache solution for an API and i'm using "cache-manager-redis-yet",  but in my organization the redis is single for all products. So we need create a prefix for the cache keys. 

**Describe the solution you'd like**

Are there any configuration option that allow me setup and create keys with prefix?  

Exemple: 

${prefixOption}:key
environment:project-name:key

PS: english from google's translator

**Comment by jaredwray** [comment]
@ezerdemello this will be released in the next 2-3 weeks.

**Comment by ezerdemello** [comment]
Jared Wray,
thanks for approve this pull request.  It will help me to solve an big
problem here.



Em qui., 9 de mai. de 2024 às 14:59, Jared Wray ***@***.***>
escreveu:
