### ISSUE TITLE
Map object is not stored

### ISSUE THREAD

**Issue by alko89** [jaredwray/cache-manager#680]
**Describe the bug**

When trying to store an object that contains a Map, it's being stored as `{"_constructor-name_":"Map"}` instead of the actual value.

**How To Reproduce (best to provide workable code or tests!)**

```typescript
import { caching } from 'cache-manager';
import { redisInsStore } from 'cache-manager-ioredis-yet';
import { Redis } from 'ioredis';

(async () => {
  const redis = new Redis('redis://localhost:6379');
  const cache = await caching(redisInsStore(redis));

  const map = new Map();
  map.set('foo', 'bar');
  map.set('baz', 'qux');
  const data = {
    foo: 'bar',
    map: map 
  };

  // Set a value
  await cache.set('data', data);

  // Get a value
  const value = await cache.get('data');
  console.log(value); // Prints out: { foo: 'bar', map: Map {} }
})().then().catch();
```

![image](https://github.com/jaredwray/cache-manager/assets/2822030/d7a25cf3-93a7-4926-8b72-cbdcda65322a)

**Comment by zph** [comment]
I just saw an error about a Map on another cache-manager plugin today and if default serialization is JSON.stringify, there's additional work needed to serialize transparently: https://github.com/rolandstarke/node-cache-manager-fs-hash/issues/14#issue-1635979064

**Comment by alko89** [comment]
@zph seems like the library already uses some form of replacer, because the Map is being serialized as `"map": {"_constructor-name_":"Map"}`, by default it's just an empty object `"map": {}`

**Comment by jaredwray** [comment]
@alko89 have you tried using the `redis` driver instead of `ioredis`?

**Comment by alko89** [comment]
hmm no, I haven't tried using different drivers, always use `ioredis`

**Comment by jaredwray** [comment]
@alko89 - please try it on redis as we added more around how to support things like this.
