### ISSUE TITLE
Broken link for 'Example Express App Usage' in README.md

### ISSUE THREAD

**Issue by julamb** [jaredwray/cache-manager#700]
Hi!

The following link seems to be broken: https://github.com/jaredwray/cache-manager/blob/main/packages/cache-manager/README.md#example-express-app-usage

I looked around a little and could not find the example anywhere on the repo.

**Comment by jaredwray** [comment]
@julamb - thanks for finding this and we have updated the usage example and put it in the table of contents. You can now get to it here: https://github.com/jaredwray/cache-manager/tree/main/packages/cache-manager#express-middleware

we also removed the bad link so people don't have this issue again. Thanks!
