### ISSUE TITLE
Del with using keyPrefix doesn't work as expected

### ISSUE THREAD

**Issue by anotheri** [jaredwray/cache-manager#709]
**Describe the bug**
There is no way to easily invalidate prefixed key

**How To Reproduce (best to provide workable code or tests!)**
- provide `redisStore` with `keyPrefix` param, e.g. `pref`
- set any value to key `test`, check that it's stored in redis as `pref:test`
- try to delete with `.del` method using the same key `test`, it won't clean up the storage (b/c it doesn't use keyPrefix for these methods: https://github.com/jaredwray/cache-manager/blob/main/packages/cache-manager-redis-yet/src/index.ts#L116-L121)

I can not see any way to get prefix from store. Is there any appropriate way to handle this scenario?

**Comment by jaredwray** [comment]
This should be resolved now.
