### ISSUE TITLE
Version 5.7.2 requires node >= 20

### ISSUE THREAD

**Issue by pandemonia** [jaredwray/cache-manager#727]
**Describe the bug**
`lru-cache` has been [updated to 11.0.0](https://www.npmjs.com/package/cache-manager/v/5.7.2?activeTab=code) with version 5.7.2, but this version [drops support for node 18](https://github.com/isaacs/node-lru-cache/blob/main/CHANGELOG.md#110).  Looks to me that the `lru-cache` version change should be a major version upgrade on `cache-manager` as well.

**How To Reproduce (best to provide workable code or tests!)**
Attempting to add the package in a node-18 environment fails:

```
❯ yarn add cache-manager                                                                                                                                             18:11:40
yarn add v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error lru-cache@11.0.0: The engine "node" is incompatible with this module. Expected version "20 || >=22". Got "18.20.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

❯ node --version                                                                                                                                                     18:11:44
v18.20.3
```

**Comment by jaredwray** [comment]
@pandemonia - did you have issues with running it as our tests said it was ok.

**Comment by victororozco** [comment]
This is because lru-cache has changed the minimum version of the nodes to >= 20

https://github.com/isaacs/node-lru-cache/commit/7965d883291e90581174d39600a7706f9cce5f95

Version 5.7.X should continue with the lru-cahe in ^10.2.2

**Comment by jaredwray** [comment]
@pandemonia @victororozco - this has now been resolved as we reverted back. Please use `cache-manager@5.7.3`
