### ISSUE TITLE
Question: how to have memory cache with dynamic TTL?

### ISSUE THREAD

**Issue by dror-weiss** [jaredwray/cache-manager#731]
I need to fetch a JWT token from a downstream service, and when it's expired I need to fetch another one.
Is this use-case relevant to the "memory" cache, or should I implement my own?

**Comment by jaredwray** [comment]
@dror-weiss I would suggest you implement your own on this. You could use our cache system and memory cash for it but realistically you end up on a hook and a refresh when it expires.
