### ISSUE TITLE
Broken links in NPM docs

### ISSUE THREAD

**Issue by DodgeWhale** [jaredwray/cache-manager#737]
**Describe the bug**

Links to docs/examples throughout https://www.npmjs.com/package/cache-manager return 404.

**How To Reproduce (best to provide workable code or tests!)**
Please provide code or unit test example that will reproduce the error. If you can't provide code, please provide a detailed description of how to reproduce the error.

(Copied from NPM page)

### Custom Stores
You can use your own custom store by creating one with the same API as the built-in memory stores.

- [Example Custom Store lru-cache](https://github.com/jaredwray/cache-manager/blob/HEAD/src/stores/memory.ts)
- [Example Custom Store redis](https://github.com/jaredwray/cache-manager/packages/cache-manager-redis-yet)
- [Example Custom Store ioredis](https://github.com/jaredwray/cache-manager/packages/cache-manager-ioredis-yet)

### Store Engines
Official and updated to last version
- [node-cache-manager-redis-yet](https://github.com/jaredwray/cache-manager/packages/cache-manager-redis-yet) (uses [node_redis](https://github.com/NodeRedis/node_redis))
- [node-cache-manager-ioredis-yet](https://github.com/jaredwray/cache-manager/packages/cache-manager-ioredis-yet) (uses [ioredis](https://github.com/luin/ioredis))

**Comment by jaredwray** [comment]
@DodgeWhale - thanks for letting us know. This has been resolved.

**Comment by DodgeWhale** [comment]
> @DodgeWhale - thanks for letting us know. This has been resolved.

No problem, thank you. I appreciate your time.
